# Time in seconds, distance in centimeters (generally)
NO_BLOCKS: 2
TIME_LIMIT:         [30, 30]
NUMBER_TO_POS:      [True, False]
BOUNDED:            [True, True]
ONLY_WHOLE_NUMBERS: [True, True]
NL_START_END:       [[0, 100], [0, 1000]]
BLOCK_LENGTH:       [5, 2]

MONITOR_WIDTH: 34
FRAME_RATE: 60
SCREEN_RES: [1920, 1080]

READY_MSG: Gotowe
READY_LETTER: 0.1
WANTED_NUMBERS: [[], []]
BANNED_RATIOS: [[], []] #as decimal fractions from 0 to 1
NL_ABS_LENGTH: 20
HATCH_LENGTH: 2
HATCH_COLOR: red
BACKGROUND_COLOR: darkgray
STIM_COLOR: dimgray
HIGHLIGHT_COLOR: white
